services:
  bot:
    image: ghcr.io/fyysikkokilta/fk-kiltisbot:latest
    env_file:
      - bot.env
    volumes:
      - ./google_service_account_creds.json:/app/google_service_account_creds.json
      - ./data:/app/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
